// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmpkkwxhxmayofjalagp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcGtrd3hoeG1heW9mamFsYWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjgyNjAsImV4cCI6MjA2MTQ0NDI2MH0.-HsCQCSBFYdKb7rrvjhoQMhCvwblCvVY8xBzvOIUJkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);